name: Run tests and publish Allure report

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Adjust this if you are using a different Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave allure-behave
          pip install playwright
          playwright install

      - name: Run Behave tests with Allure formatter
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o reports/ feature/

      - name: Load previous test report history (if any)
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: reports  # Reports directory generated by behave

      - name: Publish Allure test report to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history  # This is the directory with the generated Allure report
