name: Playwright BDD Tests with Behave

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 2: Install dependencies from requirements.txt
      - name: Install dependencies from requirements.txt
        run: |
          sudo apt-get update && sudo apt-get install -y poppler-utils
          python -m pip --version
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
          python -m pip install requirements.txt
          
          playwright install

      # Step 4: Install Playwright and its dependencies (this should install Chromium)
      - name: Install Playwright and dependencies
        run: |
          python -m playwright install --with-deps

      # Step 5: Run Behave tests
      - name: Run Behave tests
        run: |
          behave feature/ --format json --outfile result.json -v

      # Step 6: Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: behave-results
          path: result.json

      # Step 7: Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate result.json --clean -o allure-report

      # Step 8: Upload Allure report
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
