name: Run Playwright BDD Tests with Behave

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install necessary dependencies including behave and playwright

      # Step 4: Install Playwright and its dependencies
      - name: Install Playwright and its dependencies
        run: |
          python -m playwright install --with-deps  # Install Playwright browser binaries and dependencies

      # Step 5: Run Behave tests
      - name: Run Behave tests
        run: |
          behave --no-capture feature/  # Run the Behave tests in the 'feature' folder

      # Step 6: Upload test results as artifacts (optional)
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: behave-results
          path: result.json  # Make sure this path corresponds to where your Behave results are saved
