name: Playwright BDD Tests with Behave and Poetry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Step 4: Install dependencies using Poetry
      - name: Install dependencies using Poetry
        run: |
          poetry install

      # Step 5: Install system dependencies for Playwright
      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libasound2 \
            libxss1 \
            libappindicator3-1 \
            woff2  # This is usually needed for web font rendering

      # Step 6: Install Playwright and browsers
      - name: Install Playwright and dependencies
        run: |
          poetry run playwright install --with-deps

      # Step 7: Run Behave tests
      - name: Run Behave tests
        run: |
          poetry run behave feature/ --format json --outfile result.json -v  # Enable verbose logging

      # Step 8: Generate Allure report from Behave results
      - name: Generate Allure report
        run: |
          allure generate result.json --clean -o allure-report

      # Step 9: Upload Allure report as artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # Step 10: Serve Allure report (Optional for local access, not in CI)
      - name: Serve Allure report
        if: ${{ success() }}
        run: |
          allure serve allure-report/ || echo "Allure serve failed because GitHub Actions does not support serving web reports."
