name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: '00 12 * * *'  # You can re-enable this for scheduled runs if necessary.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure the filename matches exactly.

      - name: Install Playwright and its dependencies
        run: |
          python -m playwright install --with-deps

      - name: Install Allure Commandline
        run: npm install -g allure-commandline
        continue-on-error: true

      - name: Run Behave tests
        run: behave Features -f allure_behave.formatter:AllureFormatter -o Report_Json
        working-directory: .
        continue-on-error: true

      - name: Generate Allure HTML report
        run: allure generate Report_Json -o Report_Html --clean
        continue-on-error: true

      # Updated step to use actions/upload-artifact@v3
      - uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: HTML reports
          path: Report_Html
        continue-on-error: true
